# Generated by Django 5.1.1 on 2025-09-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_property_county_property_town_alter_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='ready_date',
            field=models.DateField(blank=True, help_text='Date when property becomes ready for booking', null=True),
        ),
    ]
