# Generated by Django 5.1.1 on 2025-09-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_property_ready_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.JSONField(blank=True, help_text='List of amenities available at the property', null=True),
        ),
    ]
