# Generated by Django 5.1.1 on 2025-09-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_property_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='properties/', verbose_name='Main Image'),
        ),
        migrations.AddField(
            model_name='property',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='properties/', verbose_name='Image 2'),
        ),
        migrations.AddField(
            model_name='property',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='properties/', verbose_name='Image 3'),
        ),
        migrations.AddField(
            model_name='property',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='properties/', verbose_name='Image 4'),
        ),
        migrations.AddField(
            model_name='property',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='properties/', verbose_name='Image 5'),
        ),
        migrations.AddField(
            model_name='property',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='properties/', verbose_name='Image 6'),
        ),
    ]
